### ISSUE TITLE
Does not remember user's visits if app is closed

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/UofSCTourAR#102]
If we kill app then restart it the history of places visited is reset.

![2020-04-08_08-36-28 (1)](https://user-images.githubusercontent.com/228704/78784912-30326e00-7974-11ea-8689-c7eb63c9442e.gif)

**Comment by Carabeth** [comment]
I found the same bug and it does reset achievements
![IMG_3554](https://user-images.githubusercontent.com/35968323/79696030-251af000-8248-11ea-9fc8-e2fdce01e26c.jpg)
![IMG_3554](https://user-images.githubusercontent.com/35968323/79696034-26e4b380-8248-11ea-8b13-42409d5bb638.jpg)

.

**Comment by colbyhill21** [comment]
This was fixed in PR #111
