### ISSUE TITLE
Another Horsehoe in the middle of Gervais St?

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/UofSCTourAR#103]
I'm guessing this is just for testing? Make sure you fix it by 1.0 now that we have iSpoofer.

![image](https://user-images.githubusercontent.com/228704/78785394-16ddf180-7975-11ea-8326-fd2375e24afd.png)

**Comment by Carabeth** [comment]
Di not fin this while in person on Gervais St.  Also was not found using iSpoofer.

**Comment by aylanickerson** [comment]
Not reproducible
