### ISSUE TITLE
M13: Testing Part 2

### ISSUE THREAD

**Issue by colbyhill21** [SCCapstone/UofSCTourAR#108]
- [x] Multiple unit tests (even if they are silly)

- [x] Multiple behavioral tests. Test the core functionality of the app.

- [x] In your Readme.md file add a Testing section which lists the commands/instructions one must type to run your tests, the directory (or filename regexep) where all your tests are located

**Comment by aylanickerson** [comment]
I'll be finishing up the behavioral tests in the next few days.

**Comment by aylanickerson** [comment]
Added unit tests and video tutorial for testing in the readme.
