### ISSUE TITLE
Once in History allow to view info and pictures

### ISSUE THREAD

**Issue by Carabeth** [SCCapstone/UofSCTourAR#116]
Once the locations have been visited make it so that the pictures and information are accessible from the history list.  The visited stops look as though you could tap.

**Comment by aylanickerson** [comment]
To be clear, are you looking for a similar functionality that is on the Search page? Where the user can click on the populated values and see the information about that stop? @Carabeth

**Comment by Carabeth** [comment]
Yes, I believe someone who has visited once may want to view the info from their history page at a later time.

**Comment by wlewis55** [comment]
Stops can now be access from both the Search page and Tour History page. Shows information about the stop and contains a button that takes you to the AR scene.
