### ISSUE TITLE
If you click the map where a stop is not present strange message appears

### ISSUE THREAD

**Issue by Carabeth** [SCCapstone/UofSCTourAR#117]
If you click the map where a stop is not present a strange message appears asking if you want to visit ?.  When someone says yes it defaults to last stop.

**Comment by wlewis55** [comment]
Could you post a video replicating this? I was not able to replicate it by clicking on random places on the map where there wasn’t a stop present.

**Comment by Carabeth** [comment]
I will try to get a video uploaded

**Comment by aylanickerson** [comment]
This happens at some of our test stops where we have a data point but no correlating data for that stop. We will make sure these test stops are removed.

**Comment by aylanickerson** [comment]
Removed test data, fixed null values at a couple tour stops
