### ISSUE TITLE
Magnifying glass needs small label, should add function to visited stops also

### ISSUE THREAD

**Issue by Carabeth** [SCCapstone/UofSCTourAR#118]
The magnifying glass should have a label that says all stops, it is not clear exactly what it is a search for until pressed.  (this is more enhancement than a bug).  Having the magnifying glass be a search for visited stops when on that page would be useful.  Someone may want to search places they have visited not simply all of them.  Possibly have stops greyed out in search if not visited.

**Comment by aylanickerson** [comment]
I will add a label to the search icon to make it more clear. Thanks!

**Comment by wlewis55** [comment]
UI was re done, this issue has been fixed
