### ISSUE TITLE
Double clicking on place in camera view in the wrong place removes icons other than back

### ISSUE THREAD

**Issue by Carabeth** [SCCapstone/UofSCTourAR#119]
If you double click in the wrong place instead of on the double-tap to spawn object causes icons to disappear other than the back button.  Strange artifact present, it is almost as if the object is thought to have spawned but it has not.  

![IMG_40B1A195DC9A-1](https://user-images.githubusercontent.com/35968323/79697082-9cec1900-824e-11ea-9e0d-1f514cca1e58.jpg)

**Comment by wlewis55** [comment]
See comment on #120. It is possible that the object has technically spawned, but since the environment was not properly detected, you are not able to see the object.

**Comment by Carabeth** [comment]
This is possible, hard to tell because I am testing with ispoof.
