### ISSUE TITLE
Spawn too big

### ISSUE THREAD

**Issue by Carabeth** [SCCapstone/UofSCTourAR#120]
If you double click to spawn when the object is too close it will spawn and be bigger than the screen.

![IMG_19F0371C7E57-1](https://user-images.githubusercontent.com/35968323/79697175-3f0c0100-824f-11ea-8485-0cf22e920588.jpg)

**Comment by wlewis55** [comment]
For the AR scene, we recommend about 7-10 feet in front of you (will be adding text saying that soon). This will allow the app to properly detect the floor and size the object correctly. Let us know if you get it working!
