### ISSUE TITLE
Zoom function

### ISSUE THREAD

**Issue by Carabeth** [SCCapstone/UofSCTourAR#121]
Should be able to zoom into an out in the map view.  Depending on where someone is located they may want to visit a nearby spot without physically walking so be able to zoom in and then reorient to their location would be helpful and make the app more usable for those that have difficulty getting around.  Also, would enable someone to do so when they may be unable to reach a location because of closures or construction.

**Comment by aylanickerson** [comment]
Tagged as wontfix, the lack of zoom allows the user to get a fully immersive tour experience while they are on campus, as the main purpose of the app is for the user to walk around campus and view tour stops as they would on a typical campus tour. Thank you for this feedback!
