### ISSUE TITLE
Stop called empire in Tour History/ stop object spawned but info an pictures did not. 

### ISSUE THREAD

**Issue by Carabeth** [SCCapstone/UofSCTourAR#122]
A stop listed as empire in history but this is not a stop in the search.  A stop came up that did not list info or have pictures but hitting back an trying again opened the stop, not sure if this is connected.

![IMG_A3F2F82538B0-1 2](https://user-images.githubusercontent.com/35968323/79697662-c490b080-8251-11ea-980e-2ae648fdecc0.jpg)

**Comment by aylanickerson** [comment]
Empire was a point placed for testing purposes. We will make sure this is removed!! Thank you

**Comment by aylanickerson** [comment]
Same issue present in #117

**Comment by aylanickerson** [comment]
Removed test data
