### ISSUE TITLE
Dismiss popup on menu open

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/UofSCTourAR#97]
I opened a popup then tapped on the menu and got:

![image](https://user-images.githubusercontent.com/228704/78778136-c6f92d80-7968-11ea-8a9f-ebae09b4739a.png)

The popup should go away so I can see the menu.

**Comment by Carabeth** [comment]
Not seeing this bug.

![IMG_3557](https://user-images.githubusercontent.com/35968323/79696211-4fb97880-8249-11ea-8162-f17a030b6b09.jpg)
